// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220628000715");
user_pref("extensions.lastAppVersion", "91.11.0");
user_pref("extensions.lastPlatformVersion", "91.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"b3092d88-5afb-409b-93e7-3c5d7ea7e738\",\"google@search.mozilla.org\":\"760660d1-2e47-4382-8428-cc909c1a4d83\",\"ddg@search.mozilla.org\":\"d11efed1-7550-414e-b3e9-8ab0b28f4f93\",\"amazondotcom@search.mozilla.org\":\"68b4ef3b-7491-4887-8f3f-f39f5f7aa2cb\",\"wikipedia@search.mozilla.org\":\"24dba7df-cb06-424f-a9f4-4a582aac032e\",\"bing@search.mozilla.org\":\"57c898ea-e9d5-47e4-b767-0cc99816843b\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "7f614bbb-5b39-4800-9ca6-487bb53ca08");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "eced1abd-21ab-4934-abff-7c5848022f8d");
user_pref("toolkit.telemetry.previousBuildID", "20220628000715");
