// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1680870118);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1680870118);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{1e4ac2d2-a82c-4111-87b6-4c2bae5ad7c8}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1680870113);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d026581c-ee9f-49b1-8591-5651cac6338e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230321162322");
user_pref("browser.startup.homepage_override.mstone", "111.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1680870115);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230321162322");
user_pref("extensions.lastAppVersion", "111.0.1");
user_pref("extensions.lastPlatformVersion", "111.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"0786d00d-ed91-40d0-a4fe-60ffc8674511\",\"pictureinpicture@mozilla.org\":\"8a3a1e12-a30f-4b6e-a0a2-57ce44f1a6f8\",\"screenshots@mozilla.org\":\"6e6372c2-9304-404b-bcf7-b650383c522e\",\"webcompat-reporter@mozilla.org\":\"55f2d023-3bd2-48ec-ba8a-2b285ef41cc3\",\"webcompat@mozilla.org\":\"d95058d4-48fe-4cc8-893b-6fee6195dd9b\",\"default-theme@mozilla.org\":\"15082f35-2e6c-42b6-b345-a167477f870f\",\"addons-search-detection@mozilla.com\":\"f0eb91b7-1163-4ae8-8094-5cfcc5b1e8ce\",\"google@search.mozilla.org\":\"27b09af6-715b-45d8-922c-e2c76cbde60c\",\"amazondotcom@search.mozilla.org\":\"3ee902b1-0c22-4bd0-ba97-212676d02b70\",\"wikipedia@search.mozilla.org\":\"720b9166-0d04-49a7-9e56-b6b18f6cd4cf\",\"bing@search.mozilla.org\":\"3869edca-3803-4086-bf03-0805dd242279\",\"ddg@search.mozilla.org\":\"311d9a63-4a1f-41b7-92a9-1402656534df\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e32dacb3-4429-4096-aaad-2b25e9df5a8d");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1680870111);
user_pref("toolkit.telemetry.cachedClientID", "d1736e60-ad3e-40ca-8c38-f8ac30a17261");
user_pref("toolkit.telemetry.previousBuildID", "20230321162322");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
